apiVersion: v2
name: openreplay
description: A Helm chart for Kubernetes
type: application
version: 0.3.0
AppVersion: "v1.20.0"
dependencies:
  - name: ingress-nginx
    version: "4.x.x"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress-nginx.enabled
  - name: quickwit
    version: "0.3.1"
    repository: "file://charts/quickwit"
    condition: quickwit.enabled
  - name: connector
    repository: file://charts/connector
    version: 0.1.1
    condition: connector.enabled
